grav = 7;
jump_speed = 50;
vertical_speed = 0;
jumping = false;
falling = false;
ducking = false;
terminal_velocity = 50;
dino_hp = 3;
dino_invincible = false;
gameover = false;
hurt = false;
coin_cooldown = false;
game_set_speed(30, gamespeed_fps);